version: "3"
services:
  tor:
    container_name: tor-container
    pull_policy: never
    build: 
      context: ./
      dockerfile: Dockerfile
    image: nginx:tor
    ports:
      - 8080:80
      - 4242:22
